# Generated by Django 4.1 on 2023-03-11 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=20)),
                ('area_pincode', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(max_length=6)),
                ('cust_email', models.EmailField(max_length=40, unique=True)),
                ('address', models.TextField(max_length=100)),
                ('cust_contact', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=20)),
                ('is_admin', models.IntegerField()),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField(null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssr.area')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('dri_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(max_length=6)),
                ('dri_email', models.EmailField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('dri_contact', models.BigIntegerField(unique=True)),
                ('dri_license', models.CharField(max_length=20, unique=True)),
                ('is_available', models.BooleanField(default=False, null=True)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Vehicle_Category',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('cate_type', models.CharField(max_length=20)),
                ('cate_img', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'vehicle_category',
            },
        ),
        migrations.CreateModel(
            name='Vehicle_Details',
            fields=[
                ('veh_id', models.AutoField(primary_key=True, serialize=False)),
                ('veh_no', models.CharField(max_length=15, unique=True)),
                ('chassis_no', models.CharField(max_length=20, unique=True)),
                ('rent', models.BigIntegerField()),
                ('veh_desc', models.TextField(max_length=300)),
                ('capacity', models.IntegerField()),
                ('size', models.CharField(max_length=25)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssr.vehicle_category')),
            ],
            options={
                'db_table': 'vehicle_details',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_desc', models.TextField(max_length=200)),
                ('feed_date', models.DateField()),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssr.customer')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=30)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssr.state')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_date_time', models.DateField()),
                ('pickup_address', models.TextField(max_length=100)),
                ('drop_address', models.TextField(max_length=100)),
                ('approx_km', models.IntegerField()),
                ('amount', models.IntegerField(default=False)),
                ('booking', models.IntegerField()),
                ('payment_status', models.IntegerField(default=False)),
                ('payment_type', models.IntegerField(default=False)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssr.customer')),
                ('dri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ssr.driver')),
                ('veh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssr.vehicle_details')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssr.city'),
        ),
    ]
