# Generated by Django 4.1 on 2023-03-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_category',
            name='cate_type',
            field=models.CharField(max_length=30),
        ),
    ]
