# Generated by Django 4.1 on 2023-03-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssr', '0002_alter_vehicle_category_cate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_details',
            name='veh_desc',
            field=models.TextField(max_length=500),
        ),
    ]
